version: '3'

services:
  php:
    build: './docker/php'
    volumes:
      - './app:/var/www/html'
    ports:
      - 5173:5173

  nginx:
    image: nginx:1.27.2
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'